rmdir /Q/S "C:\Apache24\manual"
del "C:\Apache24\ABOUT_APACHE.txt"
del "C:\Apache24\CHANGES.txt"
del "C:\Apache24\INSTALL.txt"
del "C:\Apache24\LICENSE.txt"
del "C:\Apache24\NOTICE.txt"
del "C:\Apache24\OPENSSL-NEWS.txt"
del "C:\Apache24\OPENSSL-README.txt"
del "C:\Apache24\README.txt"
